### PR TITLE
per-PMT maps with MC v2.4.1

### PR DESCRIPTION
**Pull request by l-althueser**
The geometry of the MC simulation has changed by a few millimeters which made it necessary to regenerate the per-PMT simulations and extract all maps with a proper coordinate system.

#### changed maps
- `XENON1T_s1_xyz_patterns_interp_corrected_MCv2.4.1.json.gz`, binned with a coarse (r, phi, z) binning. Then, since PatternFitter requires a regular/Cartesian map, use the InterpolateAndExtrapolate to generate the map for use in PAX. Not interpolated map directly binned with Cartesian map is also available on midway.
```
G4 TPC max Z: 7.4
G4 TPC min Z: -103.1
G4 TPC radius: 50.5

Extract LCE with:
Number of bins in R: 5
Number of bins in Phi: [4, 6, 8, 12, 12]
Number of bins in z: 60

Interpolate to PAX map with:
Number of bins in x: 23
Number of bins in y: 23
Number of bins in z: 60
```
- `XENON1T_s2_xy_patterns_top_corrected_MCv2.4.1.json.gz`, including only top PMTs as before. A top+bottom PMTs version is available on midway.

#### required changes in config files
- [PAX: `XENON1T.ini`](https://github.com/XENON1T/pax/blob/master/pax/config/XENON1T.ini#L262)

#### used resources
- [processing scripts as of 20.08.2018](https://github.com/XENON1T/processing/tree/15955862bc4c0eda92accf344ba57c4eef436f22)
- [MC v2.4.1](https://github.com/XENON1T/mc/releases/tag/2.4.1)

#### analysis scripts
- [per-PMT map generation S1](https://github.com/XENON1T/MCAnalysisScripts/blob/285c0f2bf7f68ddc1f2987a30e1a1331d69f129b/PerPMT_LCE_Time/Xe1T_SR1_MC_perPMT_S1.ipynb)
- [per-PMT map generation S2](https://github.com/XENON1T/MCAnalysisScripts/blob/285c0f2bf7f68ddc1f2987a30e1a1331d69f129b/PerPMT_LCE_Time/Xe1T_SR1_MC_perPMT_S2.ipynb)
- [map comparison and diagnostics](https://github.com/XENON1T/MCAnalysisScripts/blob/de3703bed54904de5a23d84d9426e877580894a3/PerPMT_LCE_Time/Xe1T_SR1_MC_perPMT_maptest.ipynb)

#### data paths
- `/project2/lgrandi/xenon1t/simulations/optPhot/mc_v2.4.1/20180821_optPhot_S1/`
- `/project2/lgrandi/xenon1t/simulations/optPhot/mc_v2.4.1/20180821_optPhot_S2/`

### CODE REVIEW

**Comment by feigaodm** [comment]
Thanks @l-althueser , do you have a few plots to check/validate the outcome of this update?

**Comment by ramirezdiego** [comment]
@l-althueser Did you find the exact commit in which the MC geometry changed? I recently moved all the 1T geometry definitions into the separate 1tTPC class, but ran several tests to confirm that nothing moved. Just to make sure I didn't mess things up, could you confirm you are referring to the changes introduced by Pietro in this [PR](https://github.com/XENON1T/mc/pull/135)?

**Comment by ramirezdiego** [comment]
OK, got some information by @feigaodm (thanks!). I understand now that the conflict comes after the ``nSort_py`` stage and that pax was simply needing the new maps, adapted to the changes in Z introduced by Pietro on the geometry. You can forget about my question, @l-althueser 😄.

**Comment by l-althueser** [comment]
@feigaodm I checked the map itself in the notebooks but didn't compared to the previous map. I wouldn't expect any significant difference other than the geometry change. So the bottom PMTs max LCE area is now shifted a bit down to the correct place. Also, the S1 map is interpolated anyway which should compensate a lot. I can try to put together a diagnostics notebook which one can use to compare any of these maps in the future.
Unfortunately, I can not compare the simulations directly since I deleted the old ones already to save space ... ;)

**Pull request merged**
