### PR TITLE
Several trigger issues

### PR DESCRIPTION
**Pull request by JelleAalbers**
This addresses several trigger issues:

* #418: read hosts from the run doc (reader.ini.mongo.hosts)
* #419 : an option `do_not_trigger` in the Trigger.DecideTriggers section that ensures no events are created at all.
* #412: The trigger periodically (every time it processes a 21.47sec batch of data) inserts a document with `data_type='batch_info'` into the trigger monitor collection for the run it is working on. This includes the timestamp and various useful info about that batch (such as number of events built, total duration of them, etc). This is not completely what @coderdj asked for: the website still needs to figure out what run the trigger is working on  -- but querying for runs with a trigger status of 'staging' or a raw data which is 'transferring' on xe1t-datamanger should accomplish this. Some old runs where the trigger crashed may also have this, so you probably want to take the latest one, or limit it to a few days old.
* #407 when the trigger crashes in the middle of a run, it will now also set the data entry in the run doc to error (as opposed to leaving it to 'transferring'). 

None of these have been tested yet.

### CODE REVIEW

**Comment by tunnell** [comment]
once tested, can merge.

**Comment by tunnell** [comment]
I mean tested on the DAQ.  Not Travis.

**Comment by JelleAalbers** [comment]
I think I found the offending bug in the trigger dead time calculation (#416), hope this will work...

**Comment by JelleAalbers** [comment]
This will be rolled out on the DAQ today or tomorrow.

**Pull request merged**
