### PR TITLE
correct typo in `add_to_z`

### PR DESCRIPTION
**Pull request by pietrodigangi**
correct typo in `add_to_z` assigned value. 
It was `add_to_z = (2.15 + 0.25) * cm` -> correct is `add_to_z = (2.15 + 0.025) * cm`

### CODE REVIEW

**Comment by feigaodm** [comment]
For Xe100 the distance between gate and liquid level is 2.5mm. If we want to set gate to 0, we need 2.5 mm instead of 10 times smaller

**Comment by feigaodm** [comment]
Maybe modify the one in Xe1T.ini file?

**Comment by pietrodigangi** [comment]
@feigaodm there was a misunderstanding with Jelle on gitter chat about that value (the typo is actually in the comment above)

**Comment by pietrodigangi** [comment]
@feigaodm for XENON1T, has this z offset to be the same with impose in the Geant4 code to have the gate at 0? I'm not sure how the value in the Xe1T.ini relates to that one in G4

**Comment by JelleAalbers** [comment]
Yes, Pietro spotted the inconsistency between comment and config, and I agreed it was a typo. However it's the comment that was incorrect while the config was ok. Should be fixed now.

**Comment by feigaodm** [comment]
@JelleAalbers Should we change the one in [XENON1T.ini](https://github.com/XENON1T/pax/blob/master/pax/config/XENON1T.ini#L179) to 0? You commented there that we should change it when G4 geometry is updated, and I think it happended long time ago.

**Comment by JelleAalbers** [comment]
Yes, if the MC files now output positions in the common coordinate system, we can change that setting to 0, and remove the override in https://github.com/XENON1T/pax/blob/master/pax/config/SimulationMCInput.ini.

**Pull request merged**
