### PR TITLE
Remove old lce

### PR DESCRIPTION
**Pull request by berget2**
Deleting depreciated LCE maps

### CODE REVIEW

**Comment by berget2** [comment]
sure!

**Comment by feigaodm** [comment]
yeah, removing that Xe100 file will cause [build error on Travis](https://travis-ci.org/XENON1T/pax/jobs/286164548#L1361). Please keep it.

**Comment by pdeperio** [comment]
@berget2 are you able to add ```s1_xyz_XENON100_xerawdp045.json``` back into this PR?  i'm not sure how, so maybe need to make a new PR and close this one.

**Comment by l-althueser** [comment]
Some git magic like multiple `git reset HEAD~` is not working, but `git checkout 22173e0~1 pax\data\s
1_xyz_XENON100_xerawdp045.json` should bring the file back. If you want to keep the history clean, you should merge as a single commit or reopen a new PR ;)

**Comment by feigaodm** [comment]
re made by PR #627

**Pull request closed without merging**
