### PR TITLE
Split dependencies into upgradable and not upgradable

### PR DESCRIPTION
**Pull request by tunnell**
About half of our dependencies cannot have their versions changed without breaking pax.  After testing in my own fork, I've been able to identify which  can be upgrade and which cannot.  The ones that cannot will be marked as ignore with pyup.

### CODE REVIEW

**Comment by tunnell** [comment]
After this, I'd setup pyup.

**Comment by feigaodm** [comment]
neat, so we disable support to python2.7 totally.

**Comment by tunnell** [comment]
Oh right, let me readd.  Uh oh... god I hope that doesn't break it again....

**Comment by feigaodm** [comment]
I think python2.7 is more painful...

**Comment by tunnell** [comment]
Good catch, let's see if it builds.

**Comment by tunnell** [comment]
@JelleAalbers what do you think about dropping 2.7 support?  Given plans anyways. If we do that, than I can move on to seeing what parts of pax we can ax.

**Comment by JelleAalbers** [comment]
@tunnell dropping py2 is fine, nobody is using it and many other projects are dropping py2 very soon too. It's always been a 'best effort' thing, and if you really need py2 you now have many pax releases you can go back to.

**Pull request merged**
