### PR TITLE
SR2 TFNN & FANN, Mar2019

### PR DESCRIPTION
**Pull request by weiyuehuan**
one more PMT 71 off.
All non-functional PMTs on top array: (1, 2, 26, 31, 62, 65, 71, 79, 87, 88, 91, 102, 118)

  * original and reconstructed TFNN position:

evt_dis

  * TFNN reconstructed error:
rec_error

### CODE REVIEW

**Comment by weiyuehuan** [comment]
@feigaodm Do you know why this PR fails?   seems python version problem?
@mcfatelin please check which run_number we need to apply with PMT 71 off.  [hax setting](https://github.com/XENON1T/hax/blob/master/hax/hax.ini#L156)

**Comment by feigaodm** [comment]
let's wait until PMT list is finalized. We don't want to change it further.

**Comment by mcfatelin** [comment]
I think in last Friday's computing meeting and in email exchange, PMT WG already confirmed about the final PMT list. See [Julien's note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:pmt:pmts_status_post_sr1).  Maybe @ershockley @CaptainCooper @skazama can double check the PMT ids.

**Comment by ershockley** [comment]
Yeah I agree, my impression was PMT list is now finalized and we're just waiting on gain model to be implemented.

**Comment by feigaodm** [comment]
Can @weiyuehuan merge PR #726 to this? It will make it easier to track.

**Comment by weiyuehuan** [comment]
Thanks! @feigaodm @mcfatelin I've combined FANN and Tensorflow NN in this PR, and closed PR #726.  let me see if I can find the problem, still can't pass the check..

**Comment by feigaodm** [comment]
oh, that's a known issue and couldn't be solved easily. It's not due to changes in this PR so you don't need to worry about it.

**Pull request merged**
